// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzbIesHB80-N-E0qo19tXd2Twsch3SlaU',
    appId: '1:404931127714:web:dddba022d4bbdf9cf7eafb',
    messagingSenderId: '404931127714',
    projectId: 'homemanagementsystem-18327',
    authDomain: 'homemanagementsystem-18327.firebaseapp.com',
    storageBucket: 'homemanagementsystem-18327.appspot.com',
    measurementId: 'G-FXMRMT93T7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAznYNLS9ZH7PPXVhCes0hVHK7m54SzbMw',
    appId: '1:404931127714:android:85b14c85039fde4cf7eafb',
    messagingSenderId: '404931127714',
    projectId: 'homemanagementsystem-18327',
    storageBucket: 'homemanagementsystem-18327.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWfIt-bVgOj28EaYycJSuofbS9YOMFxdU',
    appId: '1:404931127714:ios:817ec20350861bfdf7eafb',
    messagingSenderId: '404931127714',
    projectId: 'homemanagementsystem-18327',
    storageBucket: 'homemanagementsystem-18327.appspot.com',
    iosBundleId: 'com.example.homeManageSys',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWfIt-bVgOj28EaYycJSuofbS9YOMFxdU',
    appId: '1:404931127714:ios:817ec20350861bfdf7eafb',
    messagingSenderId: '404931127714',
    projectId: 'homemanagementsystem-18327',
    storageBucket: 'homemanagementsystem-18327.appspot.com',
    iosBundleId: 'com.example.homeManageSys',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCzbIesHB80-N-E0qo19tXd2Twsch3SlaU',
    appId: '1:404931127714:web:66f067567ca8fda9f7eafb',
    messagingSenderId: '404931127714',
    projectId: 'homemanagementsystem-18327',
    authDomain: 'homemanagementsystem-18327.firebaseapp.com',
    storageBucket: 'homemanagementsystem-18327.appspot.com',
    measurementId: 'G-9N86045F32',
  );
}
